spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/fitness
  #  url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: 12345

